--
-- Discount tables schema
--

-- Create discount_types table
CREATE TABLE IF NOT EXISTS public.discount_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description text,
    name character varying(100) NOT NULL,
    CONSTRAINT discount_types_pkey PRIMARY KEY (id),
    CONSTRAINT uk_discount_types_name UNIQUE (name)
);

-- Create discounts table with the same structure as route_prices but with amount instead of price
CREATE TABLE IF NOT EXISTS public.discounts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    route_id integer NOT NULL,
    trip_type_id integer NOT NULL,
    seat_type_id integer NOT NULL,
    amount double precision NOT NULL,
    effective_date date NOT NULL,
    discount_type_id integer NOT NULL,
    CONSTRAINT discounts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_discounts_route FOREIGN KEY (route_id) REFERENCES public.routes(id),
    CONSTRAINT fk_discounts_trip_type FOREIGN KEY (trip_type_id) REFERENCES public.trip_types(id),
    CONSTRAINT fk_discounts_seat_type FOREIGN KEY (seat_type_id) REFERENCES public.seat_types(id),
    CONSTRAINT fk_discounts_discount_type FOREIGN KEY (discount_type_id) REFERENCES public.discount_types(id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_discounts_route_id ON public.discounts(route_id);
CREATE INDEX IF NOT EXISTS idx_discounts_trip_type_id ON public.discounts(trip_type_id);
CREATE INDEX IF NOT EXISTS idx_discounts_seat_type_id ON public.discounts(seat_type_id);
CREATE INDEX IF NOT EXISTS idx_discounts_discount_type_id ON public.discounts(discount_type_id);
CREATE INDEX IF NOT EXISTS idx_discounts_effective_date ON public.discounts(effective_date);

-- Set ownership (adjust as needed for your database user)
ALTER TABLE public.discount_types OWNER TO postgres;
ALTER TABLE public.discounts OWNER TO postgres;
